spring:
  application:
    name: kyc-batchs
  profiles:
    active: dev
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: never
      table-prefix: KYC_BATCH_

logging:
  level:
    root: INFO
    com.kyc: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

