spring:
  application:
    name: kyc-batchs
  profiles:
    active: dev
  jpa:
    open-in-view: false
  batch:
    job:
      enabled: false

logging:
  level:
    root: INFO
    com.kyc: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

