spring:
  datasource:
    url: jdbc:postgresql://localhost:6000/kyc_database
    username: kyc_user
    password: kyc_pass
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

kyc:
  batch:
    executive-management:
      chunk: 10
      path: "/home/batch/executives/executives.csv"
      fields: operation, executive_number, first_name, second_name, last_name, second_last_name, rfc, phone, extension, email, id_branch

logging:
  level:
    root: INFO
    com.kyc: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.batch.item.data: DEBUG