spring:
  datasource:
    url: jdbc:postgresql://localhost:6000/landings
    username: mkt
    password: mkt
    hikari:
      maximum-pool-size: 1
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

kyc:
  batch:
    payments:
      path: /home/payments
      file: SB_PAYMENT.txt

logging:
  level:
    root: INFO
    com.kyc: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE